title: Gaminax.GitHub.io
description: Web Publishing
google_analytics: UA-73093345-1
show_downloads: false

theme: minima
github_username: gaminax

gems:
  - jekyll-mentions

plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-asciidoc

